### ISSUE TITLE
Aren't handlers nested in commands a code smell?

### ISSUE THREAD

**Issue by gisek** [vkhorikov/CqrsInPractice#3]
I'm just watching your course and one thing bugs me.

In [Segregating Commands and Queries > Commands and Queries in the Onion Architecture], you said that Commands and Queries belong to the core domain layer. That makes sense, since they act as an interface to the core domain layer.

Then in [Implementing Decorators upon Command and Query Handlers > Command and Query Handlers Best Practices] you convert Handlers to nested classes inside Commands.

To my understanding, the handlers do **not** belong to the core logic. They rather belong to the application services (in your code they even exist in "AppServices" directory). Just looking at their dependencies reveals domain impurity (e.g. SessionFactory).

It feels like you merged the 2 extreme layers from the onion architecture into one.

Could you please explain why? Or maybe, am I missing something?

**Comment by vkhorikov** [comment]
You are right. This practice is an "optimization" technique and comes at a price of not fully isolating the onion layers from each other. Conceptually, the command still doesn't know about its handler because it doesn't refer to it in any way. However, physically, they are located in the same class/file, and so you won't be able to introduce a separate DLL for the core layer. It's a trade-off and you need to decide which approach works best in your particular situation.

**Comment by gisek** [comment]
Thanks. Now it makes sense :)
